/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Santiago
 */
public class ObjetoLista extends javax.swing.JPanel {

    /**
     * Creates new form ObjetoLista
     */
    private final int id;
    private boolean eslaNotaSeleccionada;

    public ObjetoLista(int id, String titulo) {
        this.id = id;
        eslaNotaSeleccionada = false;
        initComponents();
        this.titulo.setText(String.valueOf(id) + ". " + titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        resaltador = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel2.add(titulo, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        resaltador.setBackground(new java.awt.Color(255, 255, 255));
        resaltador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resaltadorActionPerformed(evt);
            }
        });
        jPanel4.add(resaltador, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void resaltadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resaltadorActionPerformed
        if (resaltador.isSelected()) {
            if (!eslaNotaSeleccionada) {
                this.titulo.setForeground(Color.RED);
            }
        } else {
            if (!eslaNotaSeleccionada) {
                this.titulo.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_resaltadorActionPerformed

    public int getId() {
        return id;
    }

    public boolean estaSeleccionado() {
        return this.resaltador.isSelected();
    }

    public void setAsNotaSeleccionada(boolean eslaNotaSeleccionada) {
        this.eslaNotaSeleccionada = eslaNotaSeleccionada;
    }

    public boolean islaNotaSeleccionada() {
        return this.eslaNotaSeleccionada;
    }

    public JLabel getTituloJLabel() {
        return titulo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox resaltador;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
