/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Santiago
 */
public class Vista extends javax.swing.JPanel {

    private int notaSeleccionadaID;

    /**
     * Creates new form interfazPrincipalJPanel
     */
    public Vista() {
        initComponents();
        notaSeleccionadaID = 0;
        listaDeNotas.setLayout(new GridLayout(0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notaActual = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        borrarNotaJButton = new javax.swing.JButton();
        agregarNotaJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDeNotas = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Notas");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("DANIEL SANTIAGO LOPEZ GIRALDO - Actividad 5 y 6 - Arquitectura de Software - 2023");

        notaActual.setColumns(20);
        notaActual.setRows(5);
        jScrollPane1.setViewportView(notaActual);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Gestor de Notas Temporales");

        borrarNotaJButton.setText("-");

        agregarNotaJButton.setText("+");

        listaDeNotas.setBackground(new java.awt.Color(255, 255, 255));
        listaDeNotas.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(listaDeNotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarNotaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrarNotaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarNotaJButton)
                        .addGap(18, 18, 18)
                        .addComponent(borrarNotaJButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addGap(21, 21, 21)))
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void agregarNota(ObjetoLista nuevaNotaTitulo) {
        this.listaDeNotas.add(nuevaNotaTitulo);
    }

    public void limpiarLista() {
        this.listaDeNotas.removeAll();
        this.revalidarLista();
    }

    public void limpiarColoresLista() {
        for (Component objetoLista : this.listaDeNotas.getComponents()) {
            if (objetoLista instanceof ObjetoLista) {
                ObjetoLista obj = (ObjetoLista) objetoLista;
                obj.setAsNotaSeleccionada(false);
                if (!obj.estaSeleccionado()) {
                    obj.getTituloJLabel().setForeground(Color.BLACK);
                } else {
                    obj.getTituloJLabel().setForeground(Color.RED);
                }

            }
        }
        this.revalidarLista();
    }

    public JButton getAgregarNotaJButton() {
        return this.agregarNotaJButton;
    }

    public JButton getBorrarNotaJButton() {
        return this.borrarNotaJButton;
    }

    public JPanel getListaDeNotas() {
        return this.listaDeNotas;
    }

    public String getNotaActualTexto() {
        return this.notaActual.getText();

    }

    public void revalidarLista() {
        listaDeNotas.revalidate();
        listaDeNotas.repaint();
    }

    public List<Integer> getNotasSeleccionadas() {
        List<Integer> lista = new ArrayList<>();
        for (Component objetoLista : this.listaDeNotas.getComponents()) {
            if (objetoLista instanceof ObjetoLista) {
                ObjetoLista obj = (ObjetoLista) objetoLista;
                if (obj.estaSeleccionado()) {
                    lista.add(obj.getId());
                }
            }
        }

        return lista;
    }

    public void setNotaSeleccionada(int id) {
        notaSeleccionadaID = id;
    }

    public int getNotaSeleccionadaID() {
        return notaSeleccionadaID;
    }

    public JTextArea getNotaActualJTextArea() {
        return this.notaActual;
    }

    public void setNotaActual(String notaActual) {
        this.notaActual.setText(notaActual);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarNotaJButton;
    private javax.swing.JButton borrarNotaJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel listaDeNotas;
    private javax.swing.JTextArea notaActual;
    // End of variables declaration//GEN-END:variables
}
